-- SQL Script for Skanida Mobile App Database Setup (Simplified - Using auth.users directly)

-- --------------------------------------------------------
-- Table structure for table `absences`
-- --------------------------------------------------------
-- Stores attendance records, including location and photo proof.
-- The `user_id` column directly references the `auth.users.id`.

CREATE TABLE public.absences (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Reference auth.users directly
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  date date NOT NULL,
  reason text NULL,
  photo_url text NULL,
  latitude double precision NULL,
  longitude double precision NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Enable Row Level Security (RLS) for absences
ALTER TABLE public.absences ENABLE ROW LEVEL SECURITY;

-- Policy: Allow users to view their own absence records
-- This policy uses auth.uid() which corresponds to the user_id from auth.users
CREATE POLICY "Allow individual user read access for absences"
ON public.absences
FOR SELECT USING (auth.uid() = user_id);

-- Policy: Allow users to insert their own absence records
-- This policy uses auth.uid() which corresponds to the user_id from auth.users
CREATE POLICY "Allow individual user insert access for absences"
ON public.absences
FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Note: Update/Delete policies might be needed depending on app features.

-- Grant necessary permissions for authenticated users on the absences table
-- This is crucial after potentially dropping/recreating the schema or table
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT SELECT, INSERT ON TABLE public.absences TO authenticated;

-- --------------------------------------------------------
-- Storage Bucket Setup & Policies (Run AFTER creating the bucket manually/via API)
-- --------------------------------------------------------
-- The application requires a storage bucket named 'attendance-photos'.
-- Create the bucket manually in the Supabase Dashboard first.
-- Ensure the bucket is marked as PUBLIC.

-- The following policies control access to the files within the bucket.
-- Run these commands in the SQL Editor AFTER the bucket exists.

-- Policy: Allow authenticated users to upload (insert) files into the 'attendance-photos' bucket.
CREATE POLICY "Allow authenticated uploads"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK ( bucket_id = 'attendance-photos' );

-- Policy: Allow anyone (public/anon and authenticated users) to read (select) files
-- from the 'attendance-photos' bucket. This is necessary because the bucket is public
-- and the app uses getPublicUrl.
CREATE POLICY "Allow public reads"
ON storage.objects FOR SELECT
TO anon, authenticated
USING ( bucket_id = 'attendance-photos' );

-- Note: You might want to add policies for UPDATE or DELETE operations later if needed.
-- Example: Allow users to delete their own photos (requires adding a user_id column or using owner info)
-- CREATE POLICY "Allow individual delete access"
-- ON storage.objects FOR DELETE
-- TO authenticated
-- USING ( auth.uid() = owner AND bucket_id = 'attendance-photos' ); -- Adjust based on owner column

-- --------------------------------------------------------
-- End of Script
-- --------------------------------------------------------
