---
name: Lint

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened]
  workflow_dispatch:

permissions: {}

jobs:
  build:
    if: github.event_name != 'workflow_dispatch' || github.ref == 'refs/heads/develop'
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 1
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Super-linter
        uses: super-linter/super-linter@v7.3.0 # x-release-please-version
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: develop
          FILTER_REGEX_INCLUDE: \.(ts|tsx)$
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_CHECKOV: false
          VALIDATE_JSCPD: false
